#!C:\code\test\ai_upsacle_test\ai_video_upscaler\venv_py310\Scripts\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
